services:
  - type: web
    name: walkietalkie
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
